In [3]:
import torch

ModuleNotFoundError: No module named 'torch'

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.6703e-42, 0.0000e+00],
        [0.0000e+00, 6.0116e-43, 0.0000e+00]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4559, 0.2554, 0.3264],
        [0.0190, 0.1139, 0.5385],
        [0.1096, 0.4383, 0.3428],
        [0.3979, 0.9881, 0.5421],
        [0.4393, 0.5993, 0.3647]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])
